import "./globals.css";
import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";

const jakartaSans = Plus_Jakarta_Sans({
  variable: '--font-jakarta-sans',
  subsets: ['latin'],
})
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jakartaSans.variable} ${inter.variable}`}
    >
      <body className="min-h-full flex flex-col font-heading bg-gray-100">
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
