export const courses = [
    {
        name: "Red Hat Enterprise Linux",
        description: "LINUX-RHCSA-Training-Weekdays 09:00AM-12:00PM",
        tutor: "Krishna Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "AWS Cloud",
        description: "AWS-Cloud Training 09:00AM-12:00PM - Weekend",
        tutor: "Shyam Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "Docker & Kubernetes",
        description: "Docker-and-Kubernetes Training 08:30AM-11:00AM",
        tutor: "RAM Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "CCNA",
        description: "CCNA Networking 08:00PM-10:00PM - Weekend",
        tutor: "Pankaj Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "Terraform",
        description: "Terraform Training 03:00PM-05:00PM",
        tutor: "Kushal Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "Python",
        description: "Python Training - Weekend 10:00AM-12:00PM",
        tutor: "Nishant Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "OpenShift",
        description: "OpenShift Training 11:30AM-01:30PM",
        tutor: "Kushal Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "Google Cloud",
        description: "Google Cloud Training - Weekend 08:00AM-10:00AM",
        tutor: "Pushkar Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "Istio",
        description: "ISTIO Service Mesh 08:00AM-10:00AM",
        tutor: "Kushal Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "DevOps (CI-CD Tools) + Git",
        description: "DevOps (CI-CD Tools) Training 10:30AM-01:00PM",
        tutor: "RAM Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
    {
        name: "VMware vSphere",
        description: "VMware VCP Training - Weekend 08:00AM-11:00AM",
        tutor: "Shyam Sir",
        price: 16000,
        originalPrice: 26000,
        discount: "38% OFF",
    },
];